default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 24hours_Doctor
  username: postgres
  password: Pas4all@1
  host: localhost
  port: 5432

test:
  <<: *default
  database: 24hours_Doctor
  username: postgres
  password: Pas4all@1
  host: localhost
  port: 5432

production:
  <<: *default
  database: 24hours_Doctor
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
